/*
  # Allow Authenticated Users to Cache Bible Data

  1. Changes
    - Add policy allowing authenticated users to insert cache entries
    - Add policy allowing authenticated users to update cache entries
    - These policies work alongside the existing service_role policies

  2. Security
    - Only authenticated users can insert/update
    - All users (authenticated) can still read all cached content
    - This is safe because we're caching public Bible text and translations

  3. Notes
    - The cache contains public domain Bible text from Sefaria
    - Translations are generated by the app and are also safe to share
    - Multiple users can benefit from each other's cached content
*/

CREATE POLICY "Authenticated users can insert cache entries"
  ON sefaria_cache
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update cache entries"
  ON sefaria_cache
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);
