// This file is automatically generated. Do not edit it directly.
import { createClient, processLock } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const VITE_SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, VITE_SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Per-tab (in-memory) auth lock instead of the default cross-tab Web Lock.
    // navigatorLock is shared across every tab of the origin, so a stuck or
    // backgrounded tab holding it blocks getSession() in all other tabs (the
    // 8s+ hang we hit). processLock keeps locking within a single tab, so one
    // tab can never wedge another.
    // NOTE: this file is auto-generated — if it's ever regenerated, re-add this.
    lock: processLock,
  },
});
